### ISSUE TITLE
SN Alerts - 

### ISSUE THREAD

**Issue by berekese** [StamusNetworks/SELKS#107]
Hi, 
I can't check alerts in that dashboard and I dont know if its why I haven't logs there o why any info isn't been processed correctly.

Here log when I do click on "SN Alert" on main dashboard Scirius:

```
Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"link error","script_stack":["doc['alert.signature_id'].value","     ^---- HERE"],"script":"doc['alert.signature_id'].value","lang":"expression"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"logstash-tls-2018.02.22","node":"Nl5UnDlZSUykAUiPr2Hk4A","reason":{"type":"script_exception","reason":"link error","script_stack":["doc['alert.signature_id'].value","     ^---- HERE"],"script":"doc['alert.signature_id'].value","lang":"expression","caused_by":{"type":"parse_exception","reason":"Field [alert.signature_id] does not exist in mappings"}}}]},"status":500}
KbnError@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:84:18358
RequestFailure@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:84:19107
CallResponseHandlersProvider/callResponseHandlers/<@https://192.168.XX.XX/bundles/kibana.bundle.js?v=15610:29:12752
[344]/</Promise.try@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:83:22243
[344]/</Promise.map/<@https://192.168.100.XX/bundles/commons.bundle.js?v=15610:83:21588
[344]/</Promise.map@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:83:21553
callResponseHandlers@https://192.168.XX.XX/bundles/kibana.bundle.js?v=15610:29:12360
FetchTheseProvider/fetchWithStrategy/<@https://192.168.XX.XX/bundles/kibana.bundle.js?v=15610:29:623
processQueue@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:38:23621
[16]/qFactory/scheduleProcessQueue/<@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:38:23888
$eval@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:39:4607
$digest@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:39:2343
$apply@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:39:5026
done@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:37:25016
completeRequest@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:37:28702
[16]/createHttpBackend/</xhr.onload@https://192.168.XX.XX/bundles/commons.bundle.js?v=15610:37:29634
```
Thanks as always.

**Comment by pevma** [comment]
Can you try resetting your dashboards -   
From the left upper corner on the drop down menu, choose ``System settings``, click o the ``Kibana `` tab, choose ``Reset`` at the bottom of the page.

**Comment by berekese** [comment]
Hi, 
I did but I lost all dashboards. Kibana says me that "I havent dashboards"
Last logs elastic:

```
[2018-02-26T08:25:10,039][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [Nl5UnDl] failed to put mappings on indices [[[logstash-http-2018.02.26/53yv1d4WTImG3e5lwF2hWQ]]], type [SELKS]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-26T08:26:45,132][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [Nl5UnDl] failed to put mappings on indices [[[logstash-http-2018.02.26/53yv1d4WTImG3e5lwF2hWQ]]], type [SELKS]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-26T08:28:19,210][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [Nl5UnDl] failed to put mappings on indices [[[logstash-http-2018.02.26/53yv1d4WTImG3e5lwF2hWQ]]], type [SELKS]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-26T08:29:54,150][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [Nl5UnDl] failed to put mappings on indices [[[logstash-http-2018.02.26/53yv1d4WTImG3e5lwF2hWQ]]], type [SELKS]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-26T08:30:07,155][INFO ][o.e.c.r.a.AllocationService] [Nl5UnDl] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[logstash-alert-2018.02.12][1], [logstash-alert-2018.02.12][2]] ...]).
```

[IMG]http://i68.tinypic.com/112cpxw.png[/IMG]

[IMG]http://i63.tinypic.com/2yx5et4.png[/IMG]

Could you let me know default dashboard? I can export it I think, right?

Thanks.

**Comment by berekese** [comment]
BTW, I haven't info on main dashboard but I yes have alerts and traffic on eve.json, stats and fast.log:

http://i67.tinypic.com/c3gwk.jpg

**Comment by pevma** [comment]
I just tried the reset sequence on SELKS as explained earlier - it worked fine.
May be you have done some other changes that may interfere?

You could also try restarting Scirius -  ``supervisorctl restart scirius`` - see if that makes any difference.
Do you have any custom firewall rules on the server?

**Comment by berekese** [comment]
Hi, 

I tried rebooting server, services, elastic... and nothing works. I haven't any firewall (iptables and ufw disabled both). The problem is maybe timeout? are there way to increase it? or debug elastic? 
Im stuck because its right, I have a virtual box server with SELKS and I did with luck "reset dashboard"

I have this problem from a last reboot why I had server 100% cpu, I increased it cpu (KVM server) and when I started it again elastic doesn't works correctly. 

Maybe index, shards, stats or some files are blocking elastic? I don't know, only for give more information, you had worked more with python, elastic than me, i'm sure :)

My last lines on elasticlog.log
```
[2018-02-26T13:55:00,019][WARN ][o.e.t.TransportService   ] [Nl5UnDl] Transport response handler not found of id [41228]
[2018-02-26T13:55:00,019][WARN ][o.e.t.TransportService   ] [Nl5UnDl] Transport response handler not found of id [41230]
[2018-02-26T13:55:00,019][WARN ][o.e.t.TransportService   ] [Nl5UnDl] Transport response handler not found of id [41231]
[2018-02-26T13:55:00,019][WARN ][o.e.t.TransportService   ] [Nl5UnDl] Transport response handler not found of id [41232]
[2018-02-26T13:55:00,177][WARN ][o.e.t.TransportService   ] [Nl5UnDl] Transport response handler not found of id [41229]
[2018-02-26T13:55:14,442][INFO ][o.e.n.Node               ] [Nl5UnDl] stopped
[2018-02-26T13:55:14,443][INFO ][o.e.n.Node               ] [Nl5UnDl] closing ...
[2018-02-26T13:55:14,487][INFO ][o.e.n.Node               ] [Nl5UnDl] closed
[2018-02-26T13:55:16,765][INFO ][o.e.n.Node               ] [] initializing ...
[2018-02-26T13:55:17,277][INFO ][o.e.e.NodeEnvironment    ] [Nl5UnDl] using [1] data paths, mounts [[/ (/dev/vda1)]], net usable_space [27.5gb], net total_space [37.1gb], spins? [possibly], types [ext4]
[2018-02-26T13:55:17,277][INFO ][o.e.e.NodeEnvironment    ] [Nl5UnDl] heap size [1.9gb], compressed ordinary object pointers [true]
[2018-02-26T13:55:17,415][INFO ][o.e.n.Node               ] node name [Nl5UnDl] derived from node ID [Nl5UnDlZSUykAUiPr2Hk4A]; set [node.name] to override
[2018-02-26T13:55:17,415][INFO ][o.e.n.Node               ] version[5.6.8], pid[7658], build[688ecce/2018-02-16T16:46:30.010Z], OS[Linux/4.9.0-5-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_151/25.151-b12]
[2018-02-26T13:55:17,416][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [aggs-matrix-stats]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [ingest-common]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [lang-expression]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [lang-groovy]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [lang-mustache]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [lang-painless]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [parent-join]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [percolator]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [reindex]
[2018-02-26T13:55:18,847][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [transport-netty3]
[2018-02-26T13:55:18,848][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] loaded module [transport-netty4]
[2018-02-26T13:55:18,848][INFO ][o.e.p.PluginsService     ] [Nl5UnDl] no plugins loaded
[2018-02-26T13:55:21,811][INFO ][o.e.d.DiscoveryModule    ] [Nl5UnDl] using discovery type [zen]
[2018-02-26T13:55:22,518][INFO ][o.e.n.Node               ] initialized
[2018-02-26T13:55:22,518][INFO ][o.e.n.Node               ] [Nl5UnDl] starting ...
[2018-02-26T13:55:22,654][INFO ][o.e.t.TransportService   ] [Nl5UnDl] publish_address {192.168.100.79:9300}, bound_addresses {[::]:9300}
[2018-02-26T13:55:22,663][INFO ][o.e.b.BootstrapChecks    ] [Nl5UnDl] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2018-02-26T13:55:25,739][INFO ][o.e.c.s.ClusterService   ] [Nl5UnDl] new_master {Nl5UnDl}{Nl5UnDlZSUykAUiPr2Hk4A}{ciOtYknpQdSRCZrXEnsB6Q}{192.168.100.79}{192.168.100.79:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-02-26T13:55:25,782][INFO ][o.e.h.n.Netty4HttpServerTransport] [Nl5UnDl] publish_address {192.168.100.79:9200}, bound_addresses {[::]:9200}
[2018-02-26T13:55:25,782][INFO ][o.e.n.Node               ] [Nl5UnDl] started
[2018-02-26T13:55:37,523][INFO ][o.e.g.GatewayService     ] [Nl5UnDl] recovered [9] indices into cluster_state
[2018-02-26T13:55:38,211][DEBUG][o.e.a.s.TransportSearchAction] [Nl5UnDl] All shards failed for phase: [query]
[2018-02-26T13:55:38,213][WARN ][r.suppressed             ] path: /logstash-alert-2018.02.26*,logstash-alert-2018.02.27*/_search, params: {ignore_unavailable=true, index=logstash-alert-2018.02.26*,logstash-alert-2018.02.27*}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:205) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:184) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-26T13:56:08,463][INFO ][o.e.c.r.a.AllocationService] [Nl5UnDl] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0], [logstash-2018.02.26][1], [logstash-2018.02.26][0]] ...]).
```

**Comment by pevma** [comment]
Try the following.
On a working SELKS - you mentioned you have a box where things were working as expected in term of dashboards - 
- cd /usr/share/python/scirius/
- source bin/activate
- python bin/manage.py kibana_export --full
- deactivate

In the current directory you should have a full export of the default dashboards (unless you have changed something in terms of - you have custom dashboard names etc...)
So for example a file that looks something like - ``scirius-dashboards-201802261355.tar.bz2``.

Then try to import those onto the box that you have troubles with.

**Comment by berekese** [comment]
Hi, 

After reboot server, stop start Elastic, etc. finally I could import dashboards from my another server. 

Now its working fine. I will continue testing all.

In any way, good good job SELKS and thanks you for your support. Greetings.

**Comment by pevma** [comment]
Glad it worked out - thank you for trying it out!
