### ISSUE TITLE
SELKS 4.0 and Active directory authentication

### ISSUE THREAD

**Issue by VN1977** [StamusNetworks/SELKS#108]
Hello!
We had previous version of SELKS and AD integration worked well. Here is my code  which is added to local_settings.py
```
# Active Directory config
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType

# Binding and connection options
AUTH_LDAP_SERVER_URI = "ldap://kdc.domain.com:389"
AUTH_LDAP_BIND_DN = "CN=user,CN=Users,DC=domain,DC=com"
AUTH_LDAP_BIND_PASSWORD = "password"
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 0,
    ldap.OPT_REFERRALS: 0,
}

# User and group search objects and types
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=domain,DC=com",
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=domain,DC=com",
    ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()

# Cache settings
AUTH_LDAP_CACHE_GROUPS = Tcome
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 60

# What to do once the user is authenticated
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
# FQDN of AD group to be staff user
    "is_staff": ["CN=usual_users,CN=Users,DC=domain,DC=com"],	
# FQDN of AD group to be supecomser
	"is_superuser": ["CN=power_users,CN=Users,DC=domain,DC=com"]
}
AUTH_LDAP_FIND_GROUP_PERMS = True

# The backends needed to make this work.
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    `'django.contrib.auth.backends.ModelBackend')
```
But the same code doesn't work with SELKS 4.0. How to correct this problem?

**Comment by pevma** [comment]
It is probably an upgrade in the django settings that is needed as well.

**Comment by VN1977** [comment]
I guessed about this. But what exactly is wrong? Can you tell me, please? 
What is the difference beetween django at SELKS 3.0 and at SELKS 4.0?

**Comment by VN1977** [comment]
Let me clarify a bit. After adding this code and restarting scirius I see in scirius-error.log
```
[2018-02-28 17:52:06 +0000] [11126] [INFO] Starting gunicorn 19.6.0
[2018-02-28 17:52:06 +0000] [11126] [INFO] Listening at: http://127.0.0.1:8000 (11126)
[2018-02-28 17:52:06 +0000] [11126] [INFO] Using worker: sync
[2018-02-28 17:52:06 +0000] [11129] [INFO] Booting worker with pid: 11129
[2018-02-28 17:52:06 +0000] [11130] [INFO] Booting worker with pid: 11130
[2018-02-28 17:52:07 +0000] [11133] [INFO] Booting worker with pid: 11133
[2018-02-28 17:52:07 +0000] [11134] [INFO] Booting worker with pid: 11134
[2018-02-28 17:52:07 +0000] [11136] [INFO] Booting worker with pid: 11136
/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

[2018-02-28 14:52:07 +0000] [11129] [ERROR] Error handling request /rules/info
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 94, in technical_500_response
    text = reporter.get_traceback_text()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 390, in get_traceback_text
    return t.render(c)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'ol-ms-sr-rm0124.corp.lan'. You may need to add u'ol-ms-sr-rm0124.corp.lan' to ALLOWED_HOSTS.
/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

[2018-02-28 14:52:09 +0000] [11136] [ERROR] Error handling request /rules/info
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 94, in technical_500_response
    text = reporter.get_traceback_text()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 390, in get_traceback_text
    return t.render(c)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: '10.0.65.115'. You may need to add u'10.0.65.115' to ALLOWED_HOSTS.
[2018-02-28 14:52:09 +0000] [11136] [ERROR] Error handling request /rules/es?query=alerts_count&from_date=1519742559613&prev=1&hosts=*
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 94, in technical_500_response
    text = reporter.get_traceback_text()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 390, in get_traceback_text
    return t.render(c)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'ol-ms-sr-rm0124.corp.lan'. You may need to add u'ol-ms-sr-rm0124.corp.lan' to ALLOWED_HOSTS.
[2018-02-28 14:52:10 +0000] [11136] [ERROR] Error handling request /rules/info
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/base.py", line 207, in get_response
    return debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 94, in technical_500_response
    text = reporter.get_traceback_text()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/views/debug.py", line 390, in get_traceback_text
    return t.render(c)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current()
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 152, in build_absolute_uri
    host=self.get_host(),
  File "/usr/share/python/scirius/lib/python2.7/site-packages/django/http/request.py", line 102, in get_host
    raise DisallowedHost(msg)
DisallowedHost: Invalid HTTP_HOST header: 'host.domain.com'. You may need to add u'host.domain.com' to ALLOWED_HOSTS.
```

**Comment by VN1977** [comment]
I found the issue https://groups.google.com/forum/#!topic/selks/EhdSJ8LQE0Q 
Is it connected with my?

**Comment by VN1977** [comment]
Well, I solved this problem. It was because of absent ldap module. I installed it but after this I can't login absolutely. There are no errors in scirius-error.log. but a lot in browser.

```
Request Method: | POST
-- | --
https://host.domain.com/accounts/login/
1.8.18
OperationalError
no such table: my_cache_table
/usr/share/python/scirius/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
/usr/bin/python
2.7.13
['/usr/share/python/scirius/lib/python2.7/site-packages/git/ext/gitdb',  '/usr/share/python/scirius/lib/python2.7/site-packages',  '/usr/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/share/python/scirius/lib/python2.7/site-packages/gitdb/ext/smmap']
Thu, 1 Mar 2018 11:16:45 +0300 
```
In scirius-error.log only
```
/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

/usr/share/python/scirius/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

**Comment by VN1977** [comment]
and plus traceback from browser
```
Environment:


Request Method: POST
Request URL: https://host.domain.com/

Django Version: 1.8.18
Python Version: 2.7.13
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_tables2',
 'bootstrap3',
 'dbbackup',
 'rules',
 'suricata',
 'accounts',
 'revproxy')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'scirius.loginrequired.LoginRequiredMiddleware',
 'scirius.utils.TimezoneMiddleware')


Traceback:
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/share/python/scirius/lib/python2.7/site-packages/accounts/views.py" in loginview
  43.         user = authenticate(username=username, password=password)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in authenticate
  74.             user = backend.authenticate(**credentials)
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in authenticate
  148.             user = self.authenticate_ldap_user(ldap_user, password)
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in authenticate_ldap_user
  208.         return ldap_user.authenticate(password)
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in authenticate
  377.             self._authenticate_user_dn(password)
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in _authenticate_user_dn
  500.         if self.dn is None:
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in dn
  465.             self._load_user_dn()
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in _load_user_dn
  533.                 self.settings.GROUP_CACHE_TIMEOUT
File "/usr/local/lib/python2.7/dist-packages/django_auth_ldap/backend.py" in cache_get_or_set
  1033.     value = cache.get(key)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/core/cache/backends/db.py" in get
  66.                            "WHERE cache_key = %%s" % table, [key])
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/db/utils.py" in __exit__
  98.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/usr/share/python/scirius/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  318.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /accounts/login/
Exception Value: no such table: my_cache_table

```

**Comment by pevma** [comment]
We would need to look into that.

**Comment by VN1977** [comment]
Hello!
Did you have enough time to check the problem?

**Comment by pevma** [comment]
Not entirely  - did you try to use Scirius 2.0 (latest) in your tests t osee if any difference?  It is in the ``debian-test`` repo you would need to enable it first.

**Comment by VN1977** [comment]
Hello!
I try scirius 2.0. Another error:
Invalid HTTP_HOST header: 'host.domain.com'. You may need to add u'host.domain.com' to ALLOWED_HOSTS.
I added hostname to local_settings.py in ALLOWED_HOSTS but didn't help.

**Comment by pevma** [comment]
I think allowed hosts should be ``*``. Can you try?

**Comment by VN1977** [comment]
Allowed hosts is "*" by default. This config doesn't work.
``"""
Django settings for scirius project.

For more information on this file, see
https://docs.djangoproject.com/en/1.6/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.6/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = "/var/lib/scirius/"
GIT_SOURCES_BASE_DIRECTORY = os.path.join(BASE_DIR, 'git-sources/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# FIXME: generate this
SECRET_KEY = 'p7o6%vq))7h3li08c%k3id(wwo*u(^dbdmx2tv#t(tb2pr9@n-'
USE_ELASTICSEARCH = True
ELASTICSEARCH_ADDRESS = "localhost:9200"
ELASTICSEARCH_VERSION = 5
KIBANA_VERSION=4
KIBANA_INDEX = ".kibana"
KIBANA_URL = "http://localhost:5601"
KIBANA_DASHBOARDS_PATH = "/opt/selks/kibana5-dashboards/"
USE_KIBANA = True
KIBANA_PROXY = True

#SURICATA_UNIX_SOCKET = "/var/run/suricata/suricata-command.socket"

USE_EVEBOX = True
EVEBOX_ADDRESS = "localhost:5636"

USE_SURICATA_STATS = True
USE_LOGSTASH_STATS = True
STATIC_ROOT="/var/lib/scirius/static/"

DATABASES = {
  'default': {
     'ENGINE': 'django.db.backends.sqlite3',
     'NAME': os.path.join(BASE_DIR, 'db', 'db.sqlite3'),
  }
}
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups/'}

ELASTICSEARCH_LOGSTASH_ALERT_INDEX="logstash-alert-"

SURICATA_NAME_IS_HOSTNAME = True

ALLOWED_HOSTS=["*"]

# Active Directory config
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType

# Binding and connection options
AUTH_LDAP_SERVER_URI = "ldap://kdc.domain.local:389"
AUTH_LDAP_BIND_DN = "CN=test,CN=Users,DC=domain,DC=local"
AUTH_LDAP_BIND_PASSWORD = "pAssw0rd"
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 0,
    ldap.OPT_REFERRALS: 0,
}

# User and group search objects and types
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=domain,DC=local",
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=domain,DC=local",
    ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()

# Cache settings
AUTH_LDAP_CACHE_GROUPS = Tcome
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 60

# What to do once the user is authenticated
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
# FQDN of AD group to be staff user
    "is_staff": ["CN=group1,DC=domain,DC=local"],	
# FQDN of AD group to be supecomser
	"is_superuser": ["CN=group2,DC=domain,DC=local"]
}
AUTH_LDAP_FIND_GROUP_PERMS = True

# The backends needed to make this work.
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    `'django.contrib.auth.backends.ModelBackend')``

**Comment by VN1977** [comment]
Hello!
Did you have enough time to check the problem?

**Comment by pevma** [comment]
Hi, Actually i havn't checked no.
Do you have any related err logs whatsoever?

Thank you

**Comment by VN1977** [comment]
Hi, can we return to this issue and implement it in SELKS6?

**Comment by VN1977** [comment]
I have solved the problem.
First of all we need to install **python-pyldap**
 `apt-get install python-pyldap`
Then install **django-auth-ldap**
`pip install django-auth-ldap`
And finally add config for AD authentication to /etc/scirius/local_settings.py. My example is below.

```
# Active Directory config
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType

# Binding and connection options
AUTH_LDAP_SERVER_URI = "ldap://ldap.server:389"
AUTH_LDAP_BIND_DN = "CN=user,CN=Users,DC=domain,DC=lan"
AUTH_LDAP_BIND_PASSWORD = "password"
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 0,
    ldap.OPT_REFERRALS: 0,
}

# User and group search objects and types
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=domain,DC=lan",
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=domain,DC=lan",
    ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()

# What to do once the user is authenticated
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
# DN of AD group to be staff user
    "is_staff": ["CN=staff_user,OU=groups,DC=domain,DC=lan"],	
# DN of AD group to be superuser
	"is_superuser": ["CN=super_user,OU=groups,DC=domain,DC=lan"]
}
# Use LDAP group membership to calculate group permissions.
AUTH_LDAP_FIND_GROUP_PERMS = True

# The backends needed to make this work.
AUTHENTICATION_BACKENDS = (
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)
```

**Comment by pevma** [comment]
Thank you very much for posting the solution.
