### ISSUE TITLE
Exception in pipelineworker when processing data

### ISSUE THREAD

**Issue by jgallucci32** [StamusNetworks/SELKS#121]
We recently turned on our firewall to send packets to SELKS. Almost instantly we started seeing errors in logstash and data stops showing up in Evebox.

NOTE: This is a brand new install of SELKS 4.0 within the past few weeks.

Here is the error from `/var/log/logstash/logstash-plain.log`
```
[2018-05-08T18:08:16,932][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2018-05-08T18:08:17,278][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.3.1-java/vendor/GeoLite2-City.mmdb"}
[2018-05-08T18:08:17,306][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.3.1-java/vendor/GeoLite2-City.mmdb"}
[2018-05-08T18:08:17,309][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>12, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1500}
[2018-05-08T18:08:17,428][INFO ][logstash.pipeline        ] Pipeline main started
[2018-05-08T18:08:17,489][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-05-08T18:08:18,097][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `tr' for -104.8203:Float", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:344:in `convert_float'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyArray.java:2414:in `map'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:299:in `convert'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:252:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:46:in `multi_filter'", "(eval):833:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):829:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):847:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):844:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):863:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):858:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):311:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2018-05-08T18:08:18,112][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `tr' for -71.0843:Float", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:344:in `convert_float'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyArray.java:2414:in `map'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:299:in `convert'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:252:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:46:in `multi_filter'", "(eval):833:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):829:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):847:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):844:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):863:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):858:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):311:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2018-05-08T18:08:18,116][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `tr' for -118.244:Float", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:344:in `convert_float'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyArray.java:2414:in `map'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:299:in `convert'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:252:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:46:in `multi_filter'", "(eval):833:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):829:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):847:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):844:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):863:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):858:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):311:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2018-05-08T18:08:18,128][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `tr' for -118.244:Float>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:344:in `convert_float'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyArray.java:2414:in `map'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:309:in `convert'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:299:in `convert'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:252:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:46:in `multi_filter'", "(eval):833:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):829:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):847:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):844:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):863:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):858:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):311:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
```

**Comment by pevma** [comment]
It seems you have [stumbled upon the known upgrade err here](https://github.com/StamusNetworks/SELKS/wiki/SELKS-upgrades#logstash-569-breaking-upgrade) when upgrading logstash.

**Comment by jgallucci32** [comment]
I followed the instructions and changed `float` to `float_eu` but it did not resolve the issue. Was required to downgrade to logstash 5.6.8 as suggested by a previous comment to the same reported issue.

Any other suggestions?

**Comment by pevma** [comment]
Strange - It works here for me in my set up. Did you restart ES and LS services etc ?
