### ISSUE TITLE
[SELKS5] delete-old-logs.sh uses python 3.6, 3.5 latest stable version.

### ISSUE THREAD

**Issue by Jeroen0494** [StamusNetworks/SELKS#142]
When I execute the /opt/selks/delete-old-logs.sh executable I receive the following error:

```
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_singleton.py", line 24, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 1, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

The script points to python3.6 (Debian testing/unstable) but the latest version on SELKS5 is python3.5 (stable). We should either update to 3.6 or alter elastic-curator in a way that it uses version 3.5.

**Comment by pevma** [comment]
Wondering if we do it as described here  -  
https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-debian-9/
as an import from Testing - if it would work ok?

**Comment by pevma** [comment]
also seems related to `libssl.so.1.0.0`

**Comment by Jeroen0494** [comment]
I think the repository version is the most sane. That will only install from testing what's necessary and keep the package up-do-date.

**Comment by pevma** [comment]
hm - i wonder if it is not related to that  - 
https://github.com/elastic/curator/issues/1241#issuecomment-403036970

@Jeroen0494 - could you confirm if you get a chance ?

**Comment by Jeroen0494** [comment]
> hm - i wonder if it is not related to that -
> [elastic/curator#1241 (comment)](https://github.com/elastic/curator/issues/1241#issuecomment-403036970)
> 
> @Jeroen0494 - could you confirm if you get a chance ?

That works. Update the apt sources list to use debian9 instead of debian.

**Comment by pevma** [comment]
ok - could you do a pull request if you get a chance please - updating the SELKS5 repo for both ISO creation and SN-upgrade scripts?

**Comment by Jeroen0494** [comment]
Sure thing. There you go. I'm not sure whether you use elasticsearch-curator in SELKS4, but it wasn't included in the upgrade script so I added it.
