### ISSUE TITLE
4 -> 5 upgrade fails

### ISSUE THREAD

**Issue by Sc0th** [StamusNetworks/SELKS#151]
Stock 4 install - upgrade fails with the following when running the upgrade script:

++ alias 'pydoc=python -m pydoc'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ python bin/manage.py kibana_reset
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 37, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 593, in kibana_reset
    self._kibana_request('/api/spaces/space', KIBANA6_NAMESPACE)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 371, in _kibana_request
    urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by pevma** [comment]
It seems you are missing the last three commands from here - 
https://github.com/StamusNetworks/SELKS/blob/SELKS5/scripts/SELKS4-SELKS5/SN-S4-S5-Upgrade.sh
(Latest code) 
You can just re run the last three commands and see how it goes ?

> -- 
> Regards,
> Peter Manev

**Comment by Sc0th** [comment]
not sure I follow, it's one of those last three commands that is failing, namely - •python bin/manage.py kibana_reset

**Comment by Sc0th** [comment]
fixed it, I had run out of space, getting back in my box now, thx :)

**Comment by pevma** [comment]
Thanks for the feedback !
