### ISSUE TITLE
SELKS 6 upgrade or fresh install issues

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#224]
Just trying the new SELKS 6 RC1 Desktop

![Error starting ELK error on start](https://user-images.githubusercontent.com/63368223/81745526-012b8280-9473-11ea-8cfc-c44fadf73cac.PNG)

`selks-user@SK6:~$ sudo cat /var/log/elasticsearch/elasticsearch.log
[2020-05-12T16:41:39,111][INFO ][o.e.e.NodeEnvironment    ] [SK6] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [77.3gb], net total_space [88gb], types [ext4]
[2020-05-12T16:41:39,129][INFO ][o.e.e.NodeEnvironment    ] [SK6] heap size [1007.3mb], compressed ordinary object pointers [true]
[2020-05-12T16:41:39,467][INFO ][o.e.n.Node               ] [SK6] node name [SK6], node ID [tjixCyEwS_qf1mOVFvO68A], cluster name [elasticsearch]
[2020-05-12T16:41:39,468][INFO ][o.e.n.Node               ] [SK6] version[7.6.2], pid[566], build[default/deb/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z], OS[Linux/4.19.0-8-amd64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]
[2020-05-12T16:41:39,469][INFO ][o.e.n.Node               ] [SK6] JVM home [/usr/share/elasticsearch/jdk]
[2020-05-12T16:41:39,469][INFO ][o.e.n.Node               ] [SK6] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-9916908190915590194, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]
[2020-05-12T16:41:52,568][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [aggs-matrix-stats]
[2020-05-12T16:41:52,568][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [analysis-common]
[2020-05-12T16:41:52,569][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [flattened]
[2020-05-12T16:41:52,570][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [frozen-indices]
[2020-05-12T16:41:52,570][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [ingest-common]
[2020-05-12T16:41:52,570][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [ingest-geoip]
[2020-05-12T16:41:52,571][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [ingest-user-agent]
[2020-05-12T16:41:52,571][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [lang-expression]
[2020-05-12T16:41:52,571][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [lang-mustache]
[2020-05-12T16:41:52,571][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [lang-painless]
[2020-05-12T16:41:52,572][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [mapper-extras]
[2020-05-12T16:41:52,572][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [parent-join]
[2020-05-12T16:41:52,572][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [percolator]
[2020-05-12T16:41:52,573][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [rank-eval]
[2020-05-12T16:41:52,573][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [reindex]
[2020-05-12T16:41:52,573][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [repository-url]
[2020-05-12T16:41:52,573][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [search-business-rules]
[2020-05-12T16:41:52,574][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [spatial]
[2020-05-12T16:41:52,576][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [systemd]
[2020-05-12T16:41:52,577][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [transform]
[2020-05-12T16:41:52,577][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [transport-netty4]
[2020-05-12T16:41:52,577][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [vectors]
[2020-05-12T16:41:52,577][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-analytics]
[2020-05-12T16:41:52,578][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-ccr]
[2020-05-12T16:41:52,578][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-core]
[2020-05-12T16:41:52,578][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-deprecation]
[2020-05-12T16:41:52,578][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-enrich]
[2020-05-12T16:41:52,579][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-graph]
[2020-05-12T16:41:52,579][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-ilm]
[2020-05-12T16:41:52,579][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-logstash]
[2020-05-12T16:41:52,579][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-ml]
[2020-05-12T16:41:52,580][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-monitoring]
[2020-05-12T16:41:52,580][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-rollup]
[2020-05-12T16:41:52,580][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-security]
[2020-05-12T16:41:52,580][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-sql]
[2020-05-12T16:41:52,581][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-voting-only-node]
[2020-05-12T16:41:52,581][INFO ][o.e.p.PluginsService     ] [SK6] loaded module [x-pack-watcher]
[2020-05-12T16:41:52,582][INFO ][o.e.p.PluginsService     ] [SK6] no plugins loaded
[2020-05-12T16:42:05,867][INFO ][o.e.x.s.a.s.FileRolesStore] [SK6] parsed [0] roles from file [/etc/elasticsearch/roles.yml]
[2020-05-12T16:42:14,025][ERROR][o.e.b.Bootstrap          ] [SK6] Exception
org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:587) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:456) ~[elasticsearch-7.6.2.jar:7.6.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:459) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.6.2.jar:7.6.2]
[2020-05-12T16:42:14,113][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [SK6] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.6.2.jar:7.6.2]
Caused by: org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:587) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:456) ~[elasticsearch-7.6.2.jar:7.6.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:459) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.2.jar:7.6.2]
        ... 6 more`

**Comment by ManuelFFF** [comment]
Ran command "selks-upgrade_stamus" and got an error on the final step, while updating Moloch because elasticsearch.service failed to start. Outputs below:

`Job for elasticsearch.service failed because the control process exited with error code.
See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
scirius: stopped
scirius: started

Upgrading Moloch..

Warning: Transient problem: connection refused Will retry in 30 seconds. 4
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 30 seconds. 3
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 30 seconds. 2
Warning: retries left.
Warning: Transient problem: connection refused Will retry in 30 seconds. 1
Warning: retries left.
curl: (7) Failed to connect to localhost port 9200: Connection refused
\e[1m\nMoloch will not be upgraded!! Please check that Elasticsearch is up and running.

selks-user@SK6:~$ sudo systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-05-12 17:13:36 EDT; 6min ago
     Docs: http://www.elastic.co
  Process: 20742 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 20742 (code=exited, status=1/FAILURE)

May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.cli.Command.main(Command.java:90)
May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
May 12 17:13:36 SK6 elasticsearch[20742]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
May 12 17:13:36 SK6 elasticsearch[20742]: For complete error details, refer to the log at /var/log/elasticsearch/elasticsearch.log
May 12 17:13:36 SK6 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
May 12 17:13:36 SK6 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
May 12 17:13:36 SK6 systemd[1]: Failed to start Elasticsearch.


selks-user@SK6:~$ sudo journalctl -xe
May 12 17:20:34 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:34Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:34 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:34Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:35 SK6 logstash[323]: [2020-05-12T17:20:35,233][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:35 SK6 evebox[320]: 2020-05-12 17:20:35 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:36 SK6 logstash[323]: [2020-05-12T17:20:36,360][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:37 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:37Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:37 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:37Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:38 SK6 evebox[320]: 2020-05-12 17:20:38 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:39 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:39Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:39 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:39Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:40 SK6 logstash[323]: [2020-05-12T17:20:40,238][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:41 SK6 logstash[323]: [2020-05-12T17:20:41,366][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:41 SK6 evebox[320]: 2020-05-12 17:20:41 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:42 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:42Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:42 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:42Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:44 SK6 evebox[320]: 2020-05-12 17:20:44 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:44 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:44Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:44 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:44Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:45 SK6 logstash[323]: [2020-05-12T17:20:45,242][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:46 SK6 logstash[323]: [2020-05-12T17:20:46,370][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:47 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:47Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:47 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:47Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:47 SK6 evebox[320]: 2020-05-12 17:20:47 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:49 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:49Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:49 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:49Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:50 SK6 logstash[323]: [2020-05-12T17:20:50,247][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:50 SK6 evebox[320]: 2020-05-12 17:20:50 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:51 SK6 logstash[323]: [2020-05-12T17:20:51,374][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:52 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:52Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:52 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:52Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:53 SK6 evebox[320]: 2020-05-12 17:20:53 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:54 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:54Z","tags":["warning","elasticsearch","data"],"pid":20849,"message":"Unable to revive connection: http://local
May 12 17:20:54 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:54Z","tags":["warning","elasticsearch","data"],"pid":20849,"message":"No living connections"}
May 12 17:20:54 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:54Z","tags":["warning","plugins","licensing"],"pid":20849,"message":"License information could not be obtained
May 12 17:20:54 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:54Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:54 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:54Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:55 SK6 logstash[323]: [2020-05-12T17:20:55,252][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:56 SK6 logstash[323]: [2020-05-12T17:20:56,378][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:20:56 SK6 evebox[320]: 2020-05-12 17:20:56 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:57 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:57Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:57 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:57Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:20:59 SK6 evebox[320]: 2020-05-12 17:20:59 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:20:59 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:59Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:20:59 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:20:59Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:21:00 SK6 logstash[323]: [2020-05-12T17:21:00,256][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:21:01 SK6 logstash[323]: [2020-05-12T17:21:01,382][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:21:02 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:21:02Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:21:02 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:21:02Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:21:02 SK6 evebox[320]: 2020-05-12 17:21:02 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:21:04 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:21:04Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"Unable to revive connection: http://loca
May 12 17:21:04 SK6 kibana[20849]: {"type":"log","@timestamp":"2020-05-12T21:21:04Z","tags":["warning","elasticsearch","admin"],"pid":20849,"message":"No living connections"}
May 12 17:21:05 SK6 logstash[323]: [2020-05-12T17:21:05,261][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http
May 12 17:21:05 SK6 evebox[320]: 2020-05-12 17:21:05 (server.go:335) <Error> -- Failed to ping Elastic Search, delaying startup: : Get "http://localhost:9200/": dial tcp [::1]:9200: connect:
May 12 17:21:06 SK6 sudo[21601]: selks-user : TTY=pts/1 ; PWD=/home/selks-user ; USER=root ; COMMAND=/usr/bin/journalctl -xe
May 12 17:21:06 SK6 sudo[21601]: pam_unix(sudo:session): session opened for user root by selks-user(uid=0)
lines 1368-1422/1422 (END)
selks-user@SK6:~$
`

**Comment by ManuelFFF** [comment]
Another issue. After the 1st OS reboot, the network does not work. Not sure why, because the network configuration remains the same.

**Comment by ManuelFFF** [comment]
Manually added eth0 settings to and restarted network services and even did OS reboot. Still unable to have the network working again :(

**Comment by ManuelFFF** [comment]
I was able to have the network back after completely uninstalled all xfce4 components and leaving only LXDE. This may not be the final solution, but apparently there are some issues with the network handler that comes with xfce4. 

If need more testing or detail just let me know.

Good luck!

**Comment by pevma** [comment]
ok so to sum up -      
1 - elasticsearch needed  a restart before the final upgrade sequence      
2 - When rebooted one of the dhcp interfaces did not come up - but you mention this somehow was related to the GUI manager?

**Comment by ManuelFFF** [comment]
Summarizing:

1. SELKS 6 installation runs smoothly, but it is not detecting that DHCP service is not available and it is not offering me the network manual setup, like SELKS 5 does. The installer just jumps to the next step. I have to go back to Network settings and force settings, then installer realize DHCP is not available and ask me for manual network setup.
2. Once finished the installation process I always run "selks-first-time-setup_stamus" and "selks-upgrade_stamus". After the update I like to reboot the server. As long as you do not restart the server, the network will work fine, but if you restart the server, at least once, you won't be able to have the network back and working. I am not sure what is the root cause, but if I check the network manager GUI, the wired network is configured with a static IP address, just the way I want, but the OS is not using this settings for some reason. It says something like "this network device is not being managed". Then if I check "/etc/network/interfaces" there is only one network interface: the "lo". Then I manually add configuration for "eth0" and restart the network services, I take down/up that specific interface and even reboot the OS, but nothing brings the network back. The server remains isolated, cannot reach the network.
3. Since I was having some difficulties with xfce, I entirely removed all its components and rebooted OS. Network started working again and I was able to install LXDE. With the new desktop environment I can use the network and modify the settings without any issues, that is why (I'm just guessing) that I am inclined to think that xfce could have a problem with one or some of its components, that it could be creating a conflict with the network configuration.

**Comment by ManuelFFF** [comment]
Hi,

I was happy to see that you released the stable version of SELKS 6, but when I tried the deployment I realize that none of the issues reported above are resolved. 

These issues for now make me hesitate to switch to SELKS 6


Please fix and you can count on me if you need more feedback.

Thank you

**Comment by pevma** [comment]
This is actually related to a configuration specific issue in case if you run both the management and sniffing on the same interface  Documented here (in the main doc section) -  
https://github.com/StamusNetworks/SELKS/wiki/First-time-setup#management-interface

**Comment by pevma** [comment]
Point 1 seems Debian live/OS  installation related. I never maneged to reproduce that actually.

**Comment by pevma** [comment]
Thank you for the feedback !

**Comment by ManuelFFF** [comment]
Hi, 

I will be testing the above soon and providing the feedback.

Thank you

**Comment by ManuelFFF** [comment]
I am not trying the upgrade from SELKS 5 anymore. Instead I am trying SELKS 6 fresh install, then migrate all custom content from v5.

I confirmed the above solution to manage the network interface with the graphical app (NetworkManager) is working.

Thank you
