### ISSUE TITLE
Scirius unable to start

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#245]
Hi, 

After SELKS 5 server restart, I am getting error 502 Bad Gateway from Nginx when try to access Scirius or Kibana. Could you please help me troubleshoot this?

![Nginx](https://user-images.githubusercontent.com/63368223/87826889-b39f0d80-c847-11ea-90ca-f9ba227de1ad.PNG)

Thank you

**Comment by ManuelFFF** [comment]
Update:

After some internal research and comparison with another SELKS 5 machine I found the following:
* There is no python2 process listening on 127.0.0.1:8000
* The following process are not running either
www-data 13957  0.0  0.0  29716  4728 ?        S    Jun23   5:10 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600
www-data 13960  0.0  0.3 103772 25664 ?        S    Jun23   6:14 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600
www-data 13961  0.0  0.4 412684 34704 ?        S    Jun23   8:23 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600
www-data 13962  0.0  0.4 105564 32880 ?        S    Jun23   6:48 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600
www-data 13964  0.0  0.3 105056 30320 ?        S    Jun23   7:59 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600
www-data 13965  0.0  0.6 184328 56564 ?        S    Jun23   8:21 /usr/bin/python2 /usr/bin/gunicorn -w 5 scirius.wsgi -t 600

Not sure if this is the root cause for Nginx error, but at least seems to be related. Is there a way to fix this? I have restarted Nginx service several times and also restarted the SELKS server.

Any help would be greatly appreciated.

Thank you

**Comment by ManuelFFF** [comment]
Update:

I have been doing more troubleshooting. The gunicorn app is failing to start. Please check the logs below and see if you can help me to fix this. Thank you

```
user1@server1:~$ sudo tail -f /var/log/scirius-error.log
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-07-20 09:48:06 +0000] [7960] [INFO] Starting gunicorn 19.9.0
[2020-07-20 09:48:06 +0000] [7960] [INFO] Listening at: http://127.0.0.1:8000 (7960)
[2020-07-20 09:48:06 +0000] [7960] [INFO] Using worker: sync
[2020-07-20 09:48:06 +0000] [7963] [INFO] Booting worker with pid: 7963
[2020-07-20 09:48:06 +0000] [7964] [INFO] Booting worker with pid: 7964
[2020-07-20 09:48:06 +0000] [7967] [INFO] Booting worker with pid: 7967
[2020-07-20 09:48:06 +0000] [7968] [INFO] Booting worker with pid: 7968
[2020-07-20 09:48:06 +0000] [7971] [INFO] Booting worker with pid: 7971
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.9.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-07-20 09:48:08 +0000] [7984] [INFO] Starting gunicorn 19.9.0
[2020-07-20 09:48:08 +0000] [7984] [INFO] Listening at: http://127.0.0.1:8000 (7984)
[2020-07-20 09:48:08 +0000] [7984] [INFO] Using worker: sync
[2020-07-20 09:48:08 +0000] [7987] [INFO] Booting worker with pid: 7987
[2020-07-20 09:48:08 +0000] [7989] [INFO] Booting worker with pid: 7989
[2020-07-20 09:48:08 +0000] [7992] [INFO] Booting worker with pid: 7992
[2020-07-20 09:48:08 +0000] [7994] [INFO] Booting worker with pid: 7994
[2020-07-20 09:48:08 +0000] [7999] [INFO] Booting worker with pid: 7999
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.9.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-07-20 09:48:10 +0000] [8007] [INFO] Starting gunicorn 19.9.0
[2020-07-20 09:48:10 +0000] [8007] [INFO] Listening at: http://127.0.0.1:8000 (8007)
[2020-07-20 09:48:10 +0000] [8007] [INFO] Using worker: sync
[2020-07-20 09:48:10 +0000] [8010] [INFO] Booting worker with pid: 8010
[2020-07-20 09:48:10 +0000] [8012] [INFO] Booting worker with pid: 8012
[2020-07-20 09:48:10 +0000] [8016] [INFO] Booting worker with pid: 8016
[2020-07-20 09:48:10 +0000] [8018] [INFO] Booting worker with pid: 8018
[2020-07-20 09:48:10 +0000] [8023] [INFO] Booting worker with pid: 8023
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.9.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-07-20 09:48:14 +0000] [8032] [INFO] Starting gunicorn 19.9.0
[2020-07-20 09:48:14 +0000] [8032] [INFO] Listening at: http://127.0.0.1:8000 (8032)
[2020-07-20 09:48:14 +0000] [8032] [INFO] Using worker: sync
[2020-07-20 09:48:14 +0000] [8036] [INFO] Booting worker with pid: 8036
[2020-07-20 09:48:14 +0000] [8039] [INFO] Booting worker with pid: 8039
[2020-07-20 09:48:14 +0000] [8040] [INFO] Booting worker with pid: 8040
[2020-07-20 09:48:14 +0000] [8043] [INFO] Booting worker with pid: 8043
[2020-07-20 09:48:14 +0000] [8046] [INFO] Booting worker with pid: 8046
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.9.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by ManuelFFF** [comment]
Update:

If I run Scirius in dev mode it will start working as expected, but of course, this isn't the regular way it should happen. Is there a way to re-deploy Scirius (including the apps or modules it needs)? I believe all this issues comes from python 2.7 libraries. Permissions perhaps? I am not sure. That's why I need the experts :P.

```
user1@server1:/usr/share/python/scirius/bin$ sudo ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 20, 2020 - 15:44:08
Django version 1.11.29, using settings 'scirius.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by pevma** [comment]
Is that after upgrade to SELKS 6 ?
you might want to see here for some help - mainly the nginx config -https://github.com/StamusNetworks/SELKS/wiki/Kibana-did-not-load-properly ?

**Comment by ManuelFFF** [comment]
Hi @pevma ,

No, this machine is still running SELKS 5 + ELK 6.8.9

**Comment by pevma** [comment]
Can you please try SELKS 6  - the scirius there is updated etc..

**Comment by ManuelFFF** [comment]
Hi @pevma ,

I was very excited about the release of SELKS 6, but due to the issues I initially experienced with it and the short time available to test more frequently, I have not tried again, nor fully migrated to SELKS 6. The last time I was able to test, SELKS 5 was quite stable and unfortunately not so much with SELKS 6. Of course, I am referring to my personal experience only.

I was happy to be among the first testers for the new product even in RC version and to be able to help report problems before the final version.

It has been a while and I know that you work continuously to improve the product. I promise that I will test SELKS 6 as soon as possible and I will tell you how much of the reported problems have been solved (hopefully most of them: P).

I'll keep you posted.
Thank you

**Comment by ManuelFFF** [comment]
Update:

I was unable to resolve the issue involving Nginx and Gunicorn that prevents Scirius from start, due to my lack of knowledge, so I had to use a backup of the entire machine, when Scirius was still working.

The issue is resolved

Thank you
