### ISSUE TITLE
Configuración por primera vez

### ISSUE THREAD

**Issue by netermin** [StamusNetworks/SELKS#247]
Hola, tengo una pequeño problema cuando realizo los siguientes pasos : 

- selks-first-time-setup_stamus
Please supply a network interface(s) to set up SELKS Suricata IDPS thread detection on
0: enp0s3
1: lo
Please type in interface or space delimited interfaces below and hit "Enter".
Example: eth1
OR
Example: eth1 eth2 eth3

Seleccionar : enp0s3

1) FPC
2) FPC_Retain
3) NONE
Please choose an option. Type in a number and hit "Enter"  1
Enable Full Pcacket Capture

Me da el siguente error:

### Starting Moloch DB set up ###

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 9200: Conexión rehusada
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 38, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 1972, in kibana_reset
    self._create_kibana_mappings()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 1852, in _create_kibana_mappings
    if not self.client.indices.exists('.kibana'):
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 268, in exists
    return self.transport.perform_request("HEAD", _make_path(index), params=params)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 224, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1852b2f790>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1852b2f790>: Failed to establish a new connection: [Errno 111] Connection refused)
Dashboards loading set up job failed...Exiting...
### Exited with ERROR  ###

Agradezco me puedan ayudar, esto lo estoy realizando en una máquina virtual.

**Comment by pevma** [comment]
Seems ES was not up or there was no network.

**Comment by netermin** [comment]
Lo solucione amigo, por alguna razón cuando termina la instalación del selkis el servicio kibana no se inicia de forma automática, inicio el servicio y luego cuando esta corriendo ejecuto el comando de configuración inicial.
