### ISSUE TITLE
How to change FPC policy with HTTPS enabled in ELK

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#269]
Hi,

I am using SELKS 6 + ELK 7.9.2

X-Pack and HTTPS are enabled in ELK. When I installed SELKS I enabled FPC_Retain. X-Pack nor HTTPS were enabled yet. This has been consuming a lot of HDD space. Now I need to change the FPC policy to Option #1: "FPC" instead of Option #2: "FPC_Retain". I tried to use SELKS script `selks-first-time-setup_stamus`, but this script uses curl without ELK authentication, so it shows an error and it won't complete the action.

My question is: How can I change FPC policy once X-Pack and HTTPS are enabled in ELK? If there is another way to do it, either modifying the script or passing an option to the script, or re-writing this option in config file, please show me how.

Thank you

PD: Log Output

```
user1@server1:~$ sudo /usr/bin/selks-first-time-setup_stamus
START of first time setup script - Fri 30 Oct 2020 09:56:43 AM EDT

### Setting up sniffing interface  ###


Please supply a network interface(s) to set up SELKS Suricata IDPS thread detection on
0: enp2s0
1: lo
Please type in interface or space delimited interfaces below and hit "Enter".
Example: eth1
OR
Example: eth1 eth2 eth3

Configure threat detection for INTERFACE(S):
enp2s0

The supplied network interface(s):  enp2s0

DONE!
FPC - Full Packet Capture. Suricata will rotate and delete the pcap captured files.
FPC_Retain - Full Packet Capture with having Moloch's pcap retention/rotation. Keeps the pcaps as long as there is space available.
None - disable packet capture

1) FPC
2) FPC_Retain
3) NONE
Please choose an option. Type in a number and hit "Enter" 1
Enable Full Pcacket Capture

### Starting Moloch DB set up ###

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 35, in __init__
    ESData.__init__(self)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 1726, in __init__
    if get_es_major_version() == 6:
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_graphs.py", line 44, in get_es_major_version
    es_stats = ESStats(None).get()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_graphs.py", line 2071, in get
    return self._urlopen(get_es_path(STATS_URL))
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_query.py", line 207, in _urlopen
    out = urllib2.urlopen(req, timeout=self.TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 412, in _read_status
    raise BadStatusLine("No status line received - the server has closed the connection")
httplib.BadStatusLine: No status line received - the server has closed the connection
Dashboards loading set up job failed...Exiting...
### Exited with ERROR  ###


FINISH of first time setup script - Fri 30 Oct 2020 09:58:03 AM EDT

Exited with FAILED
Full log located at - /opt/selks/log/selks-first-time-setup_stamus.log
Press enter to continue
```

**Comment by pevma** [comment]
You can adjust manually  in case of X-Pack
This is the part where it needs adjustment - 
https://github.com/StamusNetworks/selks-scripts/blob/master/Scripts/Setup/selks-molochdb-init-setup_stamus#L74
Then restart the service.

**Comment by ManuelFFF** [comment]
Hi @pevma ,

Thank you for your answer, but I was unable to move forward by myself. Could you elaborate a little bit more?

Thank you in advance

**Comment by ManuelFFF** [comment]
I am not looking for setting or changing the `retention policy`. In fact I always skip this question on the setup process: "`Would you like to setup a retention policy now? (y/n)`". What I need is just change from option 2: "`FPC_Retain`" to option 1: `"FPC`".

**Comment by pevma** [comment]
Yes - I think you should try 
```
cp -f /opt/selks/Scripts/Configs/SELKS6/etc/systemd/system/molochpcapread-nonretain-selks.service /etc/systemd/system/molochpcapread-selks.service
```
then restart the service.
Please test in your QA/test environment first :)

**Comment by ManuelFFF** [comment]
Thank you for replying. Should I just copy/replace the service file and restart Moloch service?

**Comment by ManuelFFF** [comment]
I followed your advise. PCAP service seems to be working fine so far. So should I not expect more raw data being stored by Moloch from now on?

**Comment by pevma** [comment]
Should be the case.

**Comment by ManuelFFF** [comment]
Thank you very much for your help!
