### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rezafathikohi** [StamusNetworks/SELKS#278]
I wanted to install SELKS on vmware esxi 6.5 but the installation will fail. I tried to choose debian version 10 to 4 but same problem. Please help ke to solve this issue.

**Comment by pevma** [comment]
Hi,

Thanks for trying it out.
What is the err  that you get?

> -- 
> Regards,
> Peter Manev

**Comment by rezafathikohi** [comment]
I got error in install system section

**Comment by pevma** [comment]
What is the error ?

> -- 
> Regards,
> Peter Manev

**Comment by rezafathikohi** [comment]
It says installation failed and i should go back to try install the system again

**Comment by pevma** [comment]
Can you please share  a screenshot of the err ?

**Comment by the29a** [comment]
May be i have same error in installing.
selks-first-time-setup_stamus crash with:
```
Added
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/management/commands/kibana_reset.py", line 38, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 1990, in kibana_reset
    self._kibana_request('/api/spaces/space', KIBANA6_NAMESPACE)
  File "/usr/share/python/scirius/local/lib/python2.7/site-packages/rules/es_data.py", line 1739, in _kibana_request
    urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Dashboards loading set up job failed...Exiting...
### Exited with ERROR  ###
```

**Comment by orutra** [comment]
Exactly same problem as above, when running _selks-first-time-setup_stamus (VirtualBox SELKS  virtual machine, SELKS ISO without desktop)


![image](https://user-images.githubusercontent.com/3499819/101907423-d812d200-3bba-11eb-8866-d5d86920ccd3.png)

![image](https://user-images.githubusercontent.com/3499819/101907491-ef51bf80-3bba-11eb-8ad2-5f0e49c828bf.png)

![image](https://user-images.githubusercontent.com/3499819/101907878-76069c80-3bbb-11eb-9b56-e3e899597de4.png)

**Comment by pevma** [comment]
Can you please share the last 200 lines of `/var/log/elasticsearch/elasticsearch.log ` ?
Can you try restarting the elastic service? I bumped into it once and had to reboot the machine then it was fine - but thought it was a one time issue

**Comment by orutra** [comment]
I restarted the service, same problem. I have tested desktop-iso live, also in VirtualBox and the same error occurs. (strange, a few days ago I installed desktop-iso in another pc, in VMWare and it worked as expected, without errors, I don't know if the iso download files have changed recentrly)

the required log:

```
selks-user@SELKS:~$ sudo cat /var/log/elasticsearch/elasticsearch.log
[2020-12-11T13:09:57,423][INFO ][o.e.e.NodeEnvironment    ] [SELKS] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [6.4gb], net total_space [11.7gb], types [ext4]
[2020-12-11T13:09:57,656][INFO ][o.e.e.NodeEnvironment    ] [SELKS] heap size [1gb], compressed ordinary object pointers [true]
[2020-12-11T13:09:58,530][INFO ][o.e.n.Node               ] [SELKS] node name [SELKS], node ID [RAaThqGVQ5unr4Y0B6IJcg], cluster name [elasticsearch]
[2020-12-11T13:09:58,564][INFO ][o.e.n.Node               ] [SELKS] version[7.7.0], pid[513], build[default/deb/81a1e9eda8e6183f5237786246f6dced26a10eaf/2020-05-12T02:01:37.602180Z], OS[Linux/4.19.0-9-amd64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14/14+36]
[2020-12-11T13:09:58,577][INFO ][o.e.n.Node               ] [SELKS] JVM home [/usr/share/elasticsearch/jdk]
[2020-12-11T13:09:58,579][INFO ][o.e.n.Node               ] [SELKS] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-7173441245532517272, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]
selks-user@SELKS:~$ 
```

**Comment by orutra** [comment]
After more testing, I found a strange behavior, using the same host pc (ubuntu), and the same SELKS iso file (no dektop), installing SLEXKS as guest virtual machine in VirtualBox, elasticsearch fails to start, no matter how many systemctl stop/start serive. On the contrary, installing in VMWare Workstation Player (v16), elasticsearch fails to start at boot, but works after stop/start service

**Comment by pevma** [comment]
That seems very strange.
I have a couple of questions to try to narrow it down.

1. Do you have enough RAM and disk space?
2. Did you need to install vmtools ?
3. Can you please share the output please of the following:
4. `systemctl status elasticsearch`
5. ``journalctl -u elasticsearch``
6. `selks-health-check_stamus `

**Comment by orutra** [comment]
I've just made a video (uploaded on vimeo, since it's not possible uploading here). Starting a fresh install of SELKS No-Desktop (using same iso file) both in VMWare Player and VirtualBox. Both VM same configuration: 3Gb RAM, 15Gb disk, bridged network interface. Both running aside.

After som minor problems caused by keyboard multiple presses in VM's, both VM's fail to load elasticsearch at boot. VMWare VM elasticsearch suceeds  after restarting service, whereas Virtualbox doesn't (I paused the video in the second try in VirtualBox)

Video:   [https://vimeo.com/490112393](url)

**Comment by pevma** [comment]
The RAM and disk are way too small it seems - https://github.com/StamusNetworks/SELKS/wiki/First-time-setup#short-admin-and-config-intro 
`Recommended minimum basic set up for SELKS 6 is 2vCPUs 8GB RAM`

**Comment by orutra** [comment]
Thankyou so much, 

giving 4Gb RAM for VirtualBox VM, elasticsearch does not fail and starts at boot. (I know it's under recommended, but I am testing my home network with very limited hardware resources)

**Comment by pevma** [comment]
Glad you sorted it out. I suggest you adjust to recommended minimum settings nonetheless :)
