### ISSUE TITLE
Scirius won't start NGINX error 502

### ISSUE THREAD

**Issue by yehias** [StamusNetworks/SELKS#29]
I'm getting this error when I tried to run it 

Starting Scirius Django FastCGI servers: sciriusTraceback (most recent call last):
  File "/opt/selks//scirius/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/selks/scirius/rules/models.py", line 72, in <module>
    class Source(models.Model):
  File "/opt/selks/scirius/rules/models.py", line 319, in Source
    @transaction.atomic
AttributeError: 'module' object has no attribute 'atomic'

**Comment by regit** [comment]
It seems you have a really old Django running. 1.4.1 is not supported anymore and I think it may not have the atomic available. 1.4.1 has security issue and he's too old so I will not try to add code for it.

Can you try to upgrade you django version ?

**Comment by yehias** [comment]
Sure shall I do it manually or just use ap-get update?

**Comment by regit** [comment]
You are using the one in /usr/local so I would say you should remove it and apt-get update

**Comment by yehias** [comment]
I removed /usr/local/bin, /usr/bro, and /usr/elsa since all of it working on django and elasticsearch so I ran apt-get nothing happened I will try apt-get upgrade and get back to you thanks.

**Comment by yehias** [comment]
Starting Scirius Django FastCGI servers: sciriusTraceback (most recent call last):
  File "/opt/selks//scirius/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/selks/scirius/rules/models.py", line 72, in <module>
    class Source(models.Model):
  File "/opt/selks/scirius/rules/models.py", line 319, in Source
    @transaction.atomic
AttributeError: 'module' object has no attribute 'atomic'


same issue nothing happened

**Comment by pevma** [comment]
On Thu, Nov 12, 2015 at 4:42 PM, yehias <notifications@github.com> wrote:
>
> Starting Scirius Django FastCGI servers: sciriusTraceback (most recent call last):
> File "/opt/selks//scirius/manage.py", line 10, in
> execute_from_command_line(sys.argv)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/init.py", line 443, in execute_from_command_line
> utility.execute()
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/init.py", line 382, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
> self.execute(args, *options.dict)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 231, in execute
> self.validate()
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/base.py", line 266, in validate
> num_errors = get_validation_errors(s, app)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/core/management/validation.py", line 30, in get_validation_errors
> for (app_name, error) in get_app_errors().items():
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 158, in get_app_errors
> self.populate()
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 64, in populate
> self.load_app(app_name, True)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/loading.py", line 88, in load_app
> models = import_module('.models', app_name)
> File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/utils/importlib.py", line 35, in import_module
> __import(name)
> File "/opt/selks/scirius/rules/models.py", line 72, in
> class Source(models.Model):
> File "/opt/selks/scirius/rules/models.py", line 319, in Source
> @transaction.atomic
> AttributeError: 'module' object has no attribute 'atomic'
>
> same issue nothing happened


Which django version are you using now?

>
> —
> Reply to this email directly or view it on GitHub.




-- 
Regards,
Peter Manev

**Comment by yehias** [comment]
I havw 1.8.6

**Comment by pevma** [comment]
Strange - your django still reports the old version in the previous err?

**Comment by yehias** [comment]
Yes I think something goes wrong anyway I already have a full backup so im
gonna mount clonezilla img and extract desired files but I need your help
which folders and files I need so I can restore it without lose my settings

**Comment by pevma** [comment]
For which part - the database?

**Comment by yehias** [comment]
No just to fix django error I mean when I try to access selks from Web
interface I got nginx 502 error and as you see log saying some error about
django and python

**Comment by pevma** [comment]
I am sorry - I do not understand.
You are trying to save which settings?

**Comment by yehias** [comment]
I mean since that scirius not starting and im getting nginx 502 gateway
error and its seems that its django and python error maybe I can replace
some current folders amd files with the original one

**Comment by pevma** [comment]
hmmm...this might not be a good approach.
you should try using the package manager for that - otherwise you will most likely end up with more complications.
