### ISSUE TITLE
Moloch error at first setup

### ISSUE THREAD

**Issue by eglyn** [StamusNetworks/SELKS#318]
Hi :)

When I launch the first command setup (selks-first-time-setup_stamus) , I have this error at the end: 
```
### Setting up Scirius/Moloch proxy user ###

Added
Traceback (most recent call last):
  File "bin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/management/commands/kibana_reset.py", line 34, in handle
    self.kibana_reset()
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/es_data.py", line 1977, in kibana_reset
    if not os.path.isdir(self._get_dashboard_dir()):
  File "/usr/share/python/scirius/lib/python3.7/site-packages/rules/es_data.py", line 1905, in _get_dashboard_dir
    kibana7_path = getattr(settings, 'KIBANA7_DASHBOARDS_PATH')
  File "/usr/share/python/scirius/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'KIBANA7_DASHBOARDS_PATH'
Dashboards loading set up job failed...Exiting...
### Exited with ERROR  ###
```

And when I go to the url dashboard (https://127.0.0.1/app/home), I have a black screen.
In the browser console I have: 

![image](https://user-images.githubusercontent.com/24936778/120275846-3428fa00-c2b2-11eb-89f5-9cfc4dfd34b3.png)

Any idea ?

**Comment by pevma** [comment]
First time setup needs to finish correctly to set up the GUI access properly, so that would explain the second err.     
Just a question to be sure: Is this a fresh install following the setup steps in order from here the wiki here -   https://github.com/StamusNetworks/SELKS/wiki/First-time-setup

**Comment by eglyn** [comment]
Ok, I thank I have done all steps, but I missed a line in the Nginx config about the boostrap config, I compare both file too quickly ^^,
So I just copy / paste all your nginx conf in my nginx conf, and it's ok now, thx

**Comment by pevma** [comment]
Glad it is solved. Thanks for the update.
