### ISSUE TITLE
The delete-old-logs does not work!

### ISSUE THREAD

**Issue by Linn1** [StamusNetworks/SELKS#338]
I use the command "rm -rf " to delete the biggest index of ES,because the indices is too large. I don't have enough space for the large indices.But there is something goes wrong after I delete index.The log shows:
INFO    Instantiating client object
INFO    Testing client connectivity
INFO    Successfully created Elasticsearch cilent object with provide settings
ERROR  Singleton action failed due to empty index list

How can I fix this problem?
Thanks soooo much!!

**Comment by Linn1** [comment]
The log is the output of running "delete-old-logs.sh".

**Comment by pevma** [comment]
What ELK stack version do you have ? (selks-health-check_stamus will output that information)

**Comment by Linn1** [comment]
I change the day in delete-old-logs.sh and it works!
Maybe it is not a error,I think it is remind me that there is noting to delete.
By the way,I use SELKS6.0
There is another thing goes wrong. I mount a device on /data/nsm and the suricata.log showsread the pcap file permission denied!

**Comment by Linn1** [comment]
I clean the dir: /data/nsm
And then the dir is staying empty status all the time! Where are these new pcaps?

**Comment by pevma** [comment]
I think it may be related to permissions - writing the pcaps there, depending on which FPC mode you have chosen during setup - https://github.com/StamusNetworks/SELKS/wiki/First-time-setup#full-packet-capture-fpc

**Comment by Linn1** [comment]
I run "selks-first-setup_stamus" and chose FPC mode and it works! No more perimission deined!

**Comment by Linn1** [comment]
But I have another problem.I found a large dir: /data/moloch/logs/. I chekced it and found these samiliar  errors are wrote in capture.log  so many times.
suricata.c 289 suricata_paocess(): ERROR: Parse_error 1 > {"timestamp":"2021-0930T10:40:01.773996+0800","flow_id":.....}
suricata.c 289 suricata_paocess(): ERROR: Parse_error 1 > {"timestamp":"2021-0930T10:40:42.691888+0800","flow_id":.....}
It seems that there is something wrong with suricata.I use the command "rm -rf " to delete the biggest index of ES,because the indices is too large. I don't have enough space for the large indices. I don't know if it has something to do with this problem.

**Comment by Linn1** [comment]
I run "selks-first-setup_stamus",and it failed.
I cheked the log and found the main cause was the index which named .kibana.
I think it is the removed index that I delete caused this problem.

**Comment by pevma** [comment]
What selks version are you using ?
What is the output of `selks-health-check_stamus` (as requested earlier https://github.com/StamusNetworks/SELKS/issues/338#issuecomment-929002073 :) )

**Comment by DevilMorgan** [comment]
Bu kadar mi be yazik sana bên sana nê yaptim o cocuk seni bekeldi kactin

28 Eyl 2021 Sal 05:08 tarihinde Linn1 ***@***.***> şunu yazdı:

**Comment by Linn1** [comment]
I tried to go down 3 days and it still failed! THe following is the output:
root@selks:~# sh /opt/selks/delete-old-logs.sh 
2021-10-13 14:18:11,530 INFO      Instantiating client object
2021-10-13 14:18:11,531 INFO      Testing client connectivity
2021-10-13 14:18:11,537 INFO      Successfully created Elasticsearch client object with provided settings
2021-10-13 14:18:11,738 INFO      Deleting 41 selected indices: ['logstash-smtp-2021.10.10', 'logstash-2021.10.08', 'logstash-tls-2021.10.09', 'logstash-smtp-2021.10.08', 'logstash-anomaly-2021.10.09', 'logstash-fileinfo-2021.10.09', 'logstash-alert-2021.10.08', 'logstash-smb-2021.10.09', 'logstash-alert-2021.10.10', 'logstash-tls-2021.10.10', 'logstash-tls-2021.10.08', 'logstash-2021.10.09', 'logstash-dns-2021.10.10', 'logstash-fileinfo-2021.10.10', 'logstash-dhcp-2021.10.08', 'logstash-flow-2021.10.08', 'logstash-sip-2021.10.10', 'logstash-snmp-2021.10.09', 'logstash-dns-2021.10.08', 'logstash-alert-2021.10.09', 'logstash-tftp-2021.10.08', 'logstash-dhcp-2021.10.09', 'logstash-sip-2021.10.08', 'logstash-http-2021.10.10', 'logstash-ikev2-2021.10.09', 'logstash-snmp-2021.10.10', 'logstash-ikev2-2021.10.08', 'logstash-flow-2021.10.10', 'logstash-anomaly-2021.10.08', 'logstash-fileinfo-2021.10.08', 'logstash-http-2021.10.08', 'logstash-snmp-2021.10.08', 'logstash-flow-2021.10.09', 'logstash-tftp-2021.10.10', 'logstash-dns-2021.10.09', 'logstash-sip-2021.10.09', 'logstash-http-2021.10.09', 'logstash-dhcp-2021.10.10', 'logstash-2021.10.10', 'logstash-anomaly-2021.10.10', 'logstash-tftp-2021.10.09']
2021-10-13 14:18:11,738 INFO      ---deleting index logstash-smtp-2021.10.10
2021-10-13 14:18:11,738 INFO      ---deleting index logstash-2021.10.08
2021-10-13 14:18:11,738 INFO      ---deleting index logstash-tls-2021.10.09
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-smtp-2021.10.08
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-anomaly-2021.10.09
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-fileinfo-2021.10.09
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-alert-2021.10.08
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-smb-2021.10.09
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-alert-2021.10.10
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-tls-2021.10.10
2021-10-13 14:18:11,739 INFO      ---deleting index logstash-tls-2021.10.08
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-2021.10.09
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-dns-2021.10.10
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-fileinfo-2021.10.10
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-dhcp-2021.10.08
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-flow-2021.10.08
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-sip-2021.10.10
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-snmp-2021.10.09
2021-10-13 14:18:11,740 INFO      ---deleting index logstash-dns-2021.10.08
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-alert-2021.10.09
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-tftp-2021.10.08
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-dhcp-2021.10.09
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-sip-2021.10.08
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-http-2021.10.10
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-ikev2-2021.10.09
2021-10-13 14:18:11,741 INFO      ---deleting index logstash-snmp-2021.10.10
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-ikev2-2021.10.08
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-flow-2021.10.10
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-anomaly-2021.10.08
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-fileinfo-2021.10.08
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-http-2021.10.08
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-snmp-2021.10.08
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-flow-2021.10.09
2021-10-13 14:18:11,742 INFO      ---deleting index logstash-tftp-2021.10.10
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-dns-2021.10.09
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-sip-2021.10.09
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-http-2021.10.09
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-dhcp-2021.10.10
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-2021.10.10
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-anomaly-2021.10.10
2021-10-13 14:18:11,743 INFO      ---deleting index logstash-tftp-2021.10.09
2021-10-13 14:20:11,758 CRITICAL  Failed to complete action: delete_indices.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=30))

**Comment by Linn1** [comment]
The status of es is active(running). Here is the output:
```
root@selks:~# systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-09-29 17:41:58 CST; 1 weeks 6 days ago
     Docs: https://www.elastic.co
 Main PID: 1352 (java)
    Tasks: 520 (limit: 9830)
   Memory: 2.6G
   CGroup: /system.slice/elasticsearch.service
           ├─1352 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.nega
           └─1608 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

10月 13 15:44:38 selks systemd-entrypoint[1352]:         at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:286) ~[?:?]
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.ja
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73) ~[?
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at org.apache.lucene.store.OutputStreamIndexOutput.getChecksum(OutputStream
10月 13 15:44:38 selks systemd-entrypoint[1352]:         at org.apache.lucene.codecs.CodecUtil.writeCRC(CodecUtil.java:548) ~[lucene
```
I see. I won't do it again. There is nothing I can do except `rm` some files which are seemed useless to free some space.
Thanks so much for your patience.

**Comment by Linn1** [comment]
I run `selks-db-logs-clean-up` and it didn't work.
The space is 100% used.  And elasticsearch goes stop. I tried to start it but not work.
There is no space for running application! I don't know how to fix it!
