### ISSUE TITLE
live-build currently fails for scirius package

### ISSUE THREAD

**Issue by SleuthKid** [StamusNetworks/SELKS#40]
The proposed live-build command:

```
sudo ./build-debian-live.sh -g no-desktop
```

fails with the following message for the scirius package:

```
Unpacking scirius (1.1.5-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u3) ...
Setting up dbconfig-common (1.8.47+nmu3+deb8u1) ...

Creating config file /etc/dbconfig-common/config with new version
Setting up kibana-dashboards-stamus (2015052202) ...
All runlevel operations denied by policy
invoke-rc.d: policy-rc.d denied execution of start.
Setting up python-psutil (2.1.1-2) ...
Setting up python-tz (2012c+dfsg-0.1) ...
Setting up sqlite3 (3.8.7.1-1+deb8u1) ...
Setting up scirius (1.1.5-1) ...
dbconfig-common: writing config to /etc/dbconfig-common/scirius.conf

Creating config file /etc/dbconfig-common/scirius.conf with new version
creating database db.sqlite3: success.
verifying database db.sqlite3 exists: success.
populating database via scriptfile...  Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/__init__.py", line 2, in <module>
    from .tables import Table
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 15, in <module>
    from . import columns
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
    from .base import library, BoundColumn, BoundColumns, Column
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 10, in <module>
    from django_tables2.utils import Accessor, AttributeDict, OrderBy, OrderByTuple
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 111, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/__init__.py", line 2, in <module>
    from .tables import Table
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 15, in <module>
    from . import columns
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
    from .base import library, BoundColumn, BoundColumns, Column
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 10, in <module>
    from django_tables2.utils import Accessor, AttributeDict, OrderBy, OrderByTuple
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 111, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/__init__.py", line 2, in <module>
    from .tables import Table
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 15, in <module>
    from . import columns
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
    from .base import library, BoundColumn, BoundColumns, Column
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 10, in <module>
    from django_tables2.utils import Accessor, AttributeDict, OrderBy, OrderByTuple
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 111, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/__init__.py", line 2, in <module>
    from .tables import Table
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 15, in <module>
    from . import columns
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
    from .base import library, BoundColumn, BoundColumns, Column
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 10, in <module>
    from django_tables2.utils import Accessor, AttributeDict, OrderBy, OrderByTuple
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 111, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
/
done.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/__init__.py", line 2, in <module>
    from .tables import Table
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/tables.py", line 15, in <module>
    from . import columns
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/__init__.py", line 1, in <module>
    from .base import library, BoundColumn, BoundColumns, Column
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/columns/base.py", line 10, in <module>
    from django_tables2.utils import Accessor, AttributeDict, OrderBy, OrderByTuple
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 111, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
dpkg: error processing package scirius (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (215-17+deb8u3) ...
Errors were encountered while processing:
 scirius
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: config/hooks/chroot-inside-Debian-Live.chroot failed (exit non-zero). You should check for errors.
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
mv: der Aufruf von stat für „live-image-amd64.hybrid.iso“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
```

this is probably and issue with python-six and/or python-django versions available in the chroot. Adding python-six to the build-debian-live.sh in line 308 did not help.

**Comment by SleuthKid** [comment]
The missing decorator "@six.python_2_unicode_compatible" has been introduced in six>=1.9 maybe there needs to be an additional package or pip install here because debian jessie currently ships python-six version 1.8.0-1

**Comment by regit** [comment]
Hello, I've just pushed a patch that should fix the problem.

**Comment by SleuthKid** [comment]
Hi Eric - I can confirm this fixes the problem. Thank you!

**Comment by timogoosen** [comment]
Python six or python stix?

**Comment by pevma** [comment]
@timogoosen  - six - as from the patch here - 
https://github.com/StamusNetworks/SELKS/commit/71dd4953476ae410229993e0c55fa6f3cb4cce66

If I may I would suggest trying the 3.0 branch of SELKS that offers upgraded components  - Suricata,Scirius,ES,Kibana etc.
