### ISSUE TITLE
SELKS 3.0RC1

### ISSUE THREAD

**Issue by Cingrith** [StamusNetworks/SELKS#44]
Hey guys,

Thank you for providing SELKS. I really like it and I have been playing with the 3.0 RC1 build and have noticed a problem with Elasticsearch not wanting to start after running apt-get update && upgrade and now getting "Unable to get data from Elasticsearch" in Scirius and also have lost all of the functionality of Kibana and EveBox since the update.

Before running the update I was observing that it was very sluggish and would often make Kibana time out when performing queries and wasn't able to search Events in EveBox.

Can you guys help me back up and running?

**Comment by pevma** [comment]
Thanks for trying it out !  
Did you try restarting the elasticserch service after the upgrade:  
> systemctl restart elasticsearch.service

After you restart it  - are there any errs in the logs/service ?
You may need to tune the elasticsearch config for performance - depending on how many events per sec you get.

**Comment by Cingrith** [comment]
Thanks for the reply,

After running the command and looking at the elasticsearch log file; this is what I got.

> [2016-04-28 10:39:28,860][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[2016-04-28 10:39:28,860][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-04-28 10:39:28,860][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2016-04-28 10:39:28,861][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
	# allow user 'elasticsearch' mlockall
	elasticsearch soft memlock unlimited
	elasticsearch hard memlock unlimited
[2016-04-28 10:39:28,861][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2016-04-28 10:39:29,116][INFO ][node                     ] [Mirage II] version[2.3.2], pid[50720], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-04-28 10:39:29,116][INFO ][node                     ] [Mirage II] initializing ...
[2016-04-28 10:39:29,703][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [delete-by-query] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2016-04-28 10:40:01,243][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[2016-04-28 10:40:01,244][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-04-28 10:40:01,244][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2016-04-28 10:40:01,244][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
	# allow user 'elasticsearch' mlockall
	elasticsearch soft memlock unlimited
	elasticsearch hard memlock unlimited
[2016-04-28 10:40:01,245][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2016-04-28 10:40:01,522][INFO ][node                     ] [Piranha] version[2.3.2], pid[50898], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-04-28 10:40:01,522][INFO ][node                     ] [Piranha] initializing ...
[2016-04-28 10:40:02,023][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [delete-by-query] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2016-04-28 10:49:47,799][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[2016-04-28 10:49:47,800][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-04-28 10:49:47,800][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2016-04-28 10:49:47,800][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
	# allow user 'elasticsearch' mlockall
	elasticsearch soft memlock unlimited
	elasticsearch hard memlock unlimited
[2016-04-28 10:49:47,800][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2016-04-28 10:49:48,015][INFO ][node                     ] [Maestro] version[2.3.2], pid[51162], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-04-28 10:49:48,015][INFO ][node                     ] [Maestro] initializing ...
[2016-04-28 10:49:48,503][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [delete-by-query] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.1]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

>

**Comment by pevma** [comment]
Hi,

I think this is the problem   
> Plugin [delete-by-query] is incompatible with Elasticsearch  
> [2.3.2]. Was designed for version [2.3.1]  

(https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugins-delete-by-query.html)

What you need to do is:  
> sudo /usr/share/elasticsearch/bin/plugin remove delete-by-query  
> sudo /usr/share/elasticsearch/bin/plugin install delete-by-query

(apologies for the late reply)

**Comment by Cingrith** [comment]
That has worked like a charm,

**Comment by heroflex** [comment]
My Selks server is having Elasticsearch troubles. I've tried all of the above, but with no success. The server reads "Unable to get data from Elasticsearch". The service is active and green. I've tried restarting all other services but still no luck.

**Comment by pevma** [comment]
@heroflex  - If you are using SELKS 3.0RC1 - it is no longer supported. current version is 3.0 with a test upgrade [available here](https://github.com/StamusNetworks/SELKS/wiki/SELKS-3.0-to-SELKS-4.0-upgrades---testing). 
Check if your elastic search service is running - `systemctl status elasticsearch` if not (or if it says `exited` for example) - try restarting it.
Please do not comment on closed issues. You are welcome to open a new one though.
